
- name: Configure selinux permissive
  selinux:
    policy: targeted
    state: permissive

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    masked: yes

- name: Install zabbix repository
  dnf:
    name: https://repo.zabbix.com/zabbix/4.2/rhel/8/x86_64/zabbix-release-4.2-2.el8.noarch.rpm
    state: present

- name: Install packages
  dnf: 
    name: ['zabbix-agent']
    state: present
    disable_gpg_check: yes

- name: Copy configuration file
  copy:
    src: etc/zabbix/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'

- name: Restarting zabbix agent
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - zabbix-agent
